### ISSUE TITLE
Stack with inncorrect log / pass

### ISSUE THREAD

**Issue by ifkin** [IVIAKC/webservis#6]
При вводе не существующей пары логин / пасс значение ретурнится из NoSuchElementException

Давай поразмышляем над логикой, которая не будет при нормальной работе включать вброс исключения (например проверить размер полученной из бд выборки)

**Comment by IVIAKC** [comment]
Тут чисто логический недочет:

Могут быть сценарии ожидаемые и не ожидаемые.

К ожидаемым мы отнесем ситуацию, когда с клиента прилетает пара логин пасс правильный или не правильный.

К неожидаемым мы в основном относим системые ошибки.

Отсюда: ситуацию, когда юзер ввел не правильный лог / пасс нельзя рассматривать как ошибку сервера.
